### ISSUE TITLE
executable cannot execute

### ISSUE THREAD

**Issue by Nerian** [BlueTeaLondon/heroku-buildpack-libreoffice-for-heroku-18#19]
Hi,

I installed the buildpack as per the instructions. 

Aptfile
```
libsm6
libice6
libxinerama1
libdbus-glib-1-2
libharfbuzz0b
libharfbuzz-icu0
libx11-xcb1
libxcb1
```

```
heroku create --buildpack https://github.com/BlueTeaLondon/heroku-buildpack-libreoffice-for-heroku-18.git
```

And I tried to use it like this:
```
Libreconv.convert('...', '...', ENV['OFFICE_PATH'])
```

But I get the following error:

```
Errno::EACCES: Permission denied - /app/vendor/libreoffice/opt/libreoffice7.1
  libreconv (0.9.5) lib/libreconv.rb:71:in `execute_command'
  libreconv (0.9.5) lib/libreconv.rb:52:in `block in convert'
  libreconv (0.9.5) lib/libreconv.rb:50:in `convert'
  libreconv (0.9.5) lib/libreconv.rb:23:in `convert'
```

What am I doing wrong? Should I be using a different path?

Thanks

**Comment by Nerian** [comment]
Oh it turns out I didn't had to use OFFICE_PATH. It works out of box.
